# Generated by Django 5.2.11 on 2026-02-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('altman_z_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('volatility', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
